### ISSUE TITLE
Continuación: Diseño Modelo Datos DynamoDB

### ISSUE THREAD

**Issue by lucasjdr** [juanzan92/ProyectoFront#112]

**Comment by lucasjdr** [comment]
Flujo Registraron diseñado

Front > Cognito

Request
{
"email":"test123@hotmail.com",
"pass":"test123",
"address":"calle viva 123",
"telefono": "35174893793",
"cuil":"20364567383",
"dni":"36456738",
"rol":"colaborador"
}

Response
{
"id_user":"1234",
//"token":"AlgunToken",
"role":"colaborador"
}

Front > Elastic (BackEnd)
Request
{
"id_user":"1234",
"token":"AlgunToken"
}

Response Colaborador

{
"id_user":"1234",
"transacciones" :[],
}
Response Vendor

{
"id_user":"1234",
"oportunidades" :[],
"transacciones":[]
}

Elastic>DynamoDB

Request
{
"id_user":"1234"
"token":"AlgunToken"
}

Response Colaborador
{
"id_user":"1234",
"transacciones" :[],
}

Response Vendor

{
"id_user":"1234",
"oportunidades" :[],
"transacciones":[]
}

Caso de Falla los servicios devuelven codigo pertinentes como 410 - 500
JSON
{}

**Comment by yerbaszen** [comment]
1ro - Verificar los Json, que no falte ningún atributo
2do - Crear objetos en el backlog 
3ro - Crear Lambda function para que impacte en la base.

**Comment by yerbaszen** [comment]
User Controler, Entidad Controler , User Service ya estan integrados y funcionando.
