### ISSUE TITLE
[TC] Diseño flujo creación de cuenta

### ISSUE THREAD

**Issue by gabrielneil** [juanzan92/ProyectoFront#84]
Flujo de información para la suscripción de un nuevo USUARIO. 
Determinación del datos del JSON file.
 Respuesta okey - Respuesta error.

Roles - Permisos - Tokens

**Comment by juanzan92** [comment]
Flujo Registraron diseñado 

Front > Cognito

Request
 {
  "email":"test123@hotmail.com",
  "pass":"test123",
 "address":"calle viva 123",
 "telefono": "35174893793",
 "cuil":"20364567383",
"dni":"36456738"
 
}

Response
{
"id_user":"1234",
"token":"AlgunToken",
"role":"colaborador"
}


Front > Elastic (BackEnd)
Request
{
"id_user":"1234",
"token":"AlgunToken",
"rol":"colaborador"
}

Response Colaborador

{
"id_user":"1234",
"transacciones" :[],
}
Response Vendor

{
"id_user":"1234",
"oportunidades" :[],
"transacciones":[]
}

Elastic>DynamoDB

Request
{
"id_user":"1234"
"token":"AlgunToken"
}

Response Colaborador
{
"id_user":"1234",
"transacciones" :[],
}

Response Vendor

{
"id_user":"1234",
"oportunidades" :[],
"transacciones":[]
}

Caso de Falla los servicios devuelven codigo pertinentes como 410 - 500 
JSON
{<Vacio>}
